### ISSUE TITLE
Plan for MultiColumnForm

### ISSUE THREAD

**Issue by JessyRiordan** [JessyRiordan/TIY-Assignments#26]
- [ ] Make a plan re #23 
- [ ] **Text/Other**
  - [ ] Background Color: Cornflowerblue (HATE!)
  - [ ] Font Style: NOT Times New Roman
  - [ ] Span: All Caps, white
  - [ ] Placeholders: darkblue italic
  - [ ] Input: white
- [ ] **Column 1**
  - [ ] First Name - placeholder
  - [ ] Last Name - placeholder
  - [ ] Email Address - placeholder
  - [ ] Country:
    - [ ] Choose a country, etc.
  - [ ] Biography
- [ ] **Column 2**
  - [ ] Phone Number - placeholder
  - [ ] Affiliations
  - [ ] Occupation
    - [ ] Choose an occupation, etc.
  - [ ] Cat's Name - placeholder
  - [ ] Favorite Gadget - placeholder
- [ ] **Column 3**
  - [ ] Type of Talent
    - [ ] Choose a talent, etc.
  - [ ] Favorite Drink - placeholder
  - [ ] Special Power - placeholder
  - [ ] Weapon of Choice - placeholder
  - [ ] Comments
- [ ] **Button**
  - [ ] Send your Data
  - [ ] Darkblue
  - [ ] White text
- [ ] **Media Queries**
  - [ ] Desktop:
    - [ ] bigger than 800px
  - [ ] Tablet:
    - [ ] between 460px and 800px
  - [ ] Mobile:
    - [ ] smaller than 460px

**Comment by JessyRiordan** [comment]
https://github.com/TheIronYard--Orlando/2015--SUMMER--FEE/issues/214

**Comment by al-the-x** [comment]
Sample Description:

* [ ] Make a plan re #23 
* [ ] Add more checkboxes.
* [ ] Also, cowbell.

**Comment by JessyRiordan** [comment]
[Reference Implementation](http://tympanus.net/Blueprints/ResponsiveMultiColumnForm/)

**Comment by al-the-x** [comment]
What's the deal with your planning item "Span: ALL CAPS, white"...? What are you calling a `<span>`...? There's nothing on your documentation to indicate that decision, so I'm not sure what to correct you on.

**Comment by al-the-x** [comment]
Some notes on what happens to the columns at the identified breakpoints would be better, otherwise you'll be constantly referring back to the reference implementation... or trying to keep that in your own visual memory. A textual plan can be copy-pasta comments for your code files, e.g.

``` css
/**
 * - [ ] Desktop (>800px)
 *   - [ ] What changes?
 *   - [ ] No, seriously... What CSS properties?
 *   - [ ] Since we're in the CSS file and everything...
 */
@media and (min-width: 800px) {
  /* . . . */
} /* END desktop (min-width:800px)
```
