### ISSUE TITLE
Edit Task

### ISSUE THREAD

**Issue by JessyRiordan** [JessyRiordan/TIY-Assignments#7]
#### I can edit a task so that I can change the wording of the task.
- How can I edit a task? `usage: todo edit <task#> <"taskedit">`

```
$> todo ls
[ ] 1) Remember the milk

$> todo edit 1
usage: todo edit <task#> <"taskedit">

$> todo edit 1 "Remember the beer"
Edited: Task 1 to "Remember the beer"

$> todo ls
[ ] Remember the beer

```

**Comment by JessyRiordan** [comment]
https://github.com/JessyRiordan/TIY-Assignments/pull/1

**Comment by al-the-x** [comment]
Far more important, really.
